project:
  type: website
  resources: 
    - Resume.pdf

website:
  title: "Jade Liang"
  favicon: /images/circle-small.png
  
  navbar:
    pinned: true
    background: light
    foreground: dark
    right:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Work Experience
      - href: "https://jade-y-liang.github.io/beyond-the-dataset/"
        text: My Blog
      - href: projects.qmd
        text: Projects
        
  page-footer: 
    center: "&copy; 2025 Jade Liang"

format:
  html:
    theme: 
      light: flatly
    css: styles.css
    toc: true
    link-external-newwindow: true
    smooth-scroll: true




