---
title: Work Experience
favicon: images/circle-small.png
title-block-banner: true
---

### Financial Analyst, *Marcus & Millichap*
*Dec 2025 - Present*

* Automate and optimize financial data analysis workflows, reducing processing time by over 65%.
* Build and maintain Excel-based Discounted Cash Flow (DCF) models to underwrite multifamily and retail investment opportunities, forecast cash flows, and guide pricing and investment decisions.
* Collect, clean, and standardize financial data from rent rolls, P&Ls, and market comparables to support underwriting and valuation of commercial real estate assets.
* Prepare professional-grade offering memorandums (OMs) by synthesizing underwriting, financial data, and market research on sales and rent comparables into investor-ready materials.

### Math Tutor, *LA Math Tutoring*
*Jan 2026 - Present*

* Translate complex mathematical concepts into structured, step-by-step frameworks to enhance student comprehension and retention.
* Identify knowledge gaps and customize lesson strategies, improving students’ problem-solving accuracy and efficiency.

### Data Analyst Intern, *Kurma AI*
*Feb 2025 - May 2025*

* Build automated pipelines to extract raw text data and embedded images (e.g. tables, plots, figures) from research paper PDFs to train RAG and LLM models. 
* Clean extract text by removing special characters, citation patterns, and formatting inconsistencies, and implement code to exclude irrelevant images (e.g., logos, blank images).
* Research and evaluate data extraction and cleaning methods to identify the most effective techniques for producing model-ready data.

### Cashier, *Wing Cheung Co.*
*Jun 2015 - Aug 2018*

* Provided friendly, accurate service to hundreds of customers during daily transactions.
* Maintained organized, customer-friendly produce displays throughout each shift.
* Memorized and recalled prices for 35+ items to ensure fast, accurate checkout.
